site_name: Totem Programming
repo_url: https://github.com/totemmaker/TotemArduinoBoards
repo_name: Totem Arduino Boards
site_description: Documentation site for Totemmaker Totem products programming
edit_uri: ""

theme:
  name: material
  logo: assets/images/totem-logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
  features:
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/totemmaker
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/totemmaker/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/totem_maker/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Totemmaker
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCRnZOXe1bYzW8WgE3NQojFA

extra:
  analytics:
    provider: google
    property: UA-92600507-1

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
    - 'index.md'
    - 'TotemBUS.md'
    - 'new-totem-arduino.md'
    - API:
        - 'API/index.md'
        - 'API/ModuleData.md'
        - 'API/MotorDriver.md'
        - 'API/TotemModule.md'
        - 'API/TotemRobot.md'
    - Interfaces:
        - 'interfaces/index.md'
        - 'interfaces/BLE.md'
        - 'interfaces/X4.md'
    - Modules:
        - 'modules/index.md'
        - 'modules/03.md'
        - 'modules/04.md'
        - 'modules/11.md'
        - 'modules/14.md'
        - 'modules/15.md'
        - 'modules/22.md'
    - Tutorials:
        - 'tutorials/01.ArduinoSetup.md'
        - 'tutorials/02.UseThirdParty.md'
        - 'tutorials/03.UseExamples.md'
        - 'tutorials/04.SetupController.md'
        - 'tutorials/CustomAppButtons.md'
        - 'tutorials/GettingStartedX4.md'
        - 'tutorials/X4.md'
