site_name: Totem Documentation
site_url: https://docs.totemmaker.net/
repo_url: https://github.com/totemmaker/TotemArduinoBoards
repo_name: Totem Arduino Boards
site_description: Documentation site for TotemMaker products and programming
edit_uri: ""

theme:
  name: material
  logo: assets/images/totem-logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
  features:
    - content.tabs.link   # Link content tabs by name
    - content.code.copy   # Copy button for code blocks
    - navigation.expand   # Always expand navigation list
    - navigation.indexes  # Allow to specify index file for sections
    - navigation.top      # Add back to top button
    - navigation.tabs     # Render top level sections as tabs
    - navigation.sections # Render top level sections as groups
    - navigation.footer   # Footer page navigation links

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: http://discord.totemmaker.net
    - icon: fontawesome/brands/discourse
      link: https://forum.totemmaker.net
    - icon: fontawesome/brands/github
      link: https://github.com/totemmaker
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/totemmaker/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/totem_maker/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Totemmaker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Totemmaker
  analytics:
    provider: google
    property: UA-92600507-1

copyright: © Copyright 2020-2024, Totem Technology, UAB

markdown_extensions:
  - abbr       # Place tooltips on phrases
  - attr_list  # Inject CSS attributes into elements
  - admonition # Info / Warning text boxes
  - def_list   # Add tabbed definitions after :
  - md_in_html # Write Markdown inside of HTML
  - pymdownx.snippets:    # Include other files
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details      # admonition collapse / expand
  - pymdownx.highlight    # Code blocks with syntax highlighting
  - pymdownx.inlinehilite # Inline code syntax highlighting
  - pymdownx.superfences  # Nest blocks inside each other
  - pymdownx.keys         # Show keyboard keys
  - pymdownx.tabbed:      # Group content into tabs
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.caret        # Add superscript with ^^text^^
  - pymdownx.mark         # Highlight text with ==text==
  - pymdownx.tilde        # Delete and subscript ~~text~~
  - pymdownx.tasklist:    # Generate task list with checkboxes
      custom_checkbox: true
  - pymdownx.emoji:       # Add emoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search
  - redirects:
      redirect_maps:
        tutorials/01.ArduinoSetup.md: setup/index.md
        tutorials/02.UseThirdParty.md: modules/index.md
        tutorials/03.UseExamples.md: roboboard/index.md
        tutorials/04.SetupController.md: remote-control/ps-controller.md
        tutorials/CustomAppButtons.md: remote-control/app/custom-function.md
        tutorials/GettingStartedX4.md: roboboard-x4/index.md
        tutorials/X4.md: roboboard-x4/index.md
        API/index.md: roboboard/api/index.md
        API/ModuleData.md: modules/ble/index.md
        API/MotorDriver.md: modules/ble/index.md
        API/TotemModule.md: modules/ble/index.md
        API/TotemRobot.md: modules/ble/index.md
        interfaces/index.md: modules/index.md
        interfaces/BLE.md: modules/ble/index.md
        mini-control-board-x3/index.md: modules/mini-control-board.md
        mini-control-board/index.md: modules/mini-control-board.md
        mini-control-board/revisions.md: modules/mini-control-board.md
        roboboard-x4/getting-started.md: roboboard-x4/index.md
        labboard/serial/api.md: modules/labboard.md
        labboard/serial/protocol.md: labboard/serial-protocol.md
        modules/programming.md: modules/legacy-x4/index.md
        modules/03.md: modules/roboboard-x3.md
        modules/04.md: modules/roboboard-x4.md
        remote-control/arduino/index.md: modules/index.md
        remote-control/arduino/ModuleData.md: modules/ble/index.md
        remote-control/arduino/MotorDriver.md: modules/ble/index.md
        remote-control/arduino/TotemModule.md: modules/ble/index.md
        remote-control/arduino/TotemRobot.md: modules/ble/index.md

nav:
    - "Product list" : index.md
    - "Setup":
        - 'setup/index.md'
        - "RoboBoard":
            - 'Arduino IDE 2.3' : 'setup/arduino-ide-2.md'
            - 'Arduino IDE 1.8' : 'setup/arduino-ide.md'
            - 'PlatformIO' : 'setup/platformio.md'
            - 'ESP-IDF' : 'setup/esp-idf-cmd.md'
        - "TotemDuino":
            - 'Arduino IDE' : 'totemduino/setup.md'
    - "Mini Lab":
        - 'mini-lab/index.md'
        - 'mini-lab/getting-started.md'
        - 'mini-lab/power.md'
        - "TotemDuino":
            - 'totemduino/index.md'
            - 'totemduino/driver-install.md'
            - 'totemduino/setup.md'
            - 'totemduino/schematics.md'
            - 'totemduino/micro-lab.md'
        - "LabBoard":
            - 'labboard/index.md'
            - 'labboard/main-screen.md'
            - "Features":
                - 'labboard/features/index.md'
                - 'labboard/features/setup.md'
                - 'labboard/features/pulse-counter.md'
                - 'labboard/features/frequency-meter.md'
                - 'labboard/features/pulse-generator.md'
                - '4. Serial monitor' : 'labboard/features/serial-monitor.md'
                - 'labboard/features/i2c-scanner.md'
                - 'labboard/features/dht11-monitor.md'
                - 'labboard/features/ad9833-control.md'
            - 'labboard/serial-protocol.md'
            - 'labboard/schematics.md'
            - 'labboard/firmware-update.md'
            - 'labboard/revisions.md'
        - "Side panels":
            - 'side-panels/index.md'
            - '#1 I/O panel' : 'side-panels/io-panel.md'
            - '#2 Sensor panel' : 'side-panels/sensor-panel.md'
            - '#3 Audio panel' : 'side-panels/audio-panel.md'
    - "RoboBoard":
        - 'roboboard/index.md'
        - 'RoboBoard X3' : 'roboboard-x3/index.md'
        - 'RoboBoard X4' : 'roboboard-x4/index.md'
        - "API Reference":
            - 'roboboard/api/index.md'
            - 'ESP32' : 'roboboard/api/esp32.md'
            - 'GPIO / Qwiic' : 'roboboard/api/gpio-qwiic.md'
            - 'TotemApp.' : 'roboboard/api/totemapp.md'
            - 'CAN. (X4)' : 'roboboard/api/can.md'
        - "Motor control":
            - 'Drivetrain.' : 'roboboard/api/drivetrain.md'
            - 'Servo.' : 'roboboard/api/servo.md'
            - 'DC.' : 'roboboard/api/dc.md'
        - "Board control":
            - 'Board.' : 'roboboard/api/board.md'
            - 'Button.' : 'roboboard/api/button.md'
            - 'Battery.' : 'roboboard/api/battery.md'
            - 'LED.' : 'roboboard/api/led.md'
            - 'RGB.' : 'roboboard/api/rgb.md'
            - 'IMU.' : 'roboboard/api/imu.md'
    - "Modules":
        - 'modules/index.md'
        - 'BLE Boards':
            - 'modules/ble/index.md'
            - 'modules/mini-control-board.md'
            - 'modules/roboboard-x3.md'
            - 'modules/roboboard-x4.md'
        - 'Mini Lab':
            - 'modules/labboard.md'
        - 'X4 Modules (legacy)':
            - 'modules/legacy-x4/index.md'
            - 'modules/11.md'
            - 'modules/14.md'
            - 'modules/15.md'
            - 'modules/22.md'
    - "Products":
        - 'products/index.md'
        - 'products/robotics-kits.md'
        - 'Tools':
            - 'products/screwdrivers.md'
            - 'products/board-cutters.md'
            - 'products/beam-cutters.md'
        - 'Mechanics':
            - 'products/mechanics/index.md'
            - 'products/motors.md'
            - 'products/beams.md'
            - 'products/boards.md'
            - 'products/brackets.md'
            - 'products/fasteners.md'
    - "Remote control":
        - 'remote-control/index.md'
        - "Totem App":
            - 'remote-control/app/index.md'
            - 'remote-control/app/control-robot.md'
            - 'remote-control/app/custom-function.md'
        - "PS3/PS4 controller" : remote-control/ps-controller.md
    - 'support.md'
