site_name: Totem Documentation
repo_url: https://github.com/totemmaker/TotemArduinoBoards
repo_name: Totem Arduino Boards
site_description: Documentation site for TotemMaker products and programming
edit_uri: ""

theme:
  name: material
  logo: assets/images/totem-logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
  features:
    - navigation.indexes # Allow to specify index file for sections
    - navigation.top      # Add back to top button
    - navigation.tabs     # Render top level sections as tabs
    - navigation.sections # Render top level sections as groups

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/totemmaker
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/totemmaker/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/totem_maker/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Totemmaker
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCRnZOXe1bYzW8WgE3NQojFA
  analytics:
    provider: google
    property: UA-92600507-1

markdown_extensions:
  - abbr       # Place tooltips on phrases
  - attr_list  # Inject CSS attributes into elements
  - admonition # Info / Warning text boxes
  - def_list   # Add tabbed definitions after :
  - md_in_html # Write Markdown inside of HTML
  - pymdownx.snippets     # Include other files
  - pymdownx.details      # admonition collapse / expand
  - pymdownx.highlight    # Code blocks with syntax highlighting
  - pymdownx.inlinehilite # Inline code syntax highlighting
  - pymdownx.superfences  # Nest blocks inside each other
  - pymdownx.keys         # Show keyboard keys
  - pymdownx.tabbed:      # Group content into tabs
      alternate_style: true 
  - pymdownx.caret        # Add superscript with ^^text^^
  - pymdownx.mark         # Highlight text with ==text==
  - pymdownx.tilde        # Delete and subscript ~~text~~
  - pymdownx.tasklist:    # Generate task list with checkboxes
      custom_checkbox: true
  - pymdownx.emoji:       # Add emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - redirects:
      redirect_maps:
        tutorials/01.ArduinoSetup.md: setup/index.md
        tutorials/02.UseThirdParty.md: remote-control/arduino/index.md
        tutorials/03.UseExamples.md: roboboard-x4/index.md
        tutorials/04.SetupController.md: remote-control/ps-controller.md
        tutorials/CustomAppButtons.md: remote-control/app/custom-function.md
        tutorials/GettingStartedX4.md: roboboard-x4/getting-started.md
        tutorials/X4.md: roboboard-x4/index.md
        API/index.md: remote-control/index.md
        API/ModuleData.md: remote-control/arduino/ModuleData.md
        API/MotorDriver.md: remote-control/arduino/MotorDriver.md
        API/TotemModule.md: remote-control/arduino/TotemModule.md
        API/TotemRobot.md: remote-control/arduino/TotemRobot.md
        interfaces/index.md: remote-control/arduino/index.md
        interfaces/BLE.md: remote-control/arduino/index.md

nav:
    - "Product list" : index.md
    - "Setup":
        - 'setup/index.md'
        - 'Arduino IDE' : 'setup/arduino-ide.md'
        - 'PlatformIO' : 'setup/platformio.md'
    - "Mini Lab":
        - 'mini-lab/index.md'
        - 'mini-lab/getting-started.md'
        - 'mini-lab/power.md'
        - "TotemDuino":
            - 'totemduino/index.md'
            - 'totemduino/driver-install.md'
            - 'totemduino/setup.md'
            - 'totemduino/schematics.md'
            - 'totemduino/micro-lab.md'
        - "LabBoard":
            - 'labboard/index.md'
            - 'labboard/main-screen.md'
            - "Features":
                - 'labboard/features/index.md'
                - 'labboard/features/setup.md'
                - 'labboard/features/pulse-counter.md'
                - 'labboard/features/frequency-counter.md'
                - 'labboard/features/pulse-generator.md'
                - 'labboard/features/serial-monitor.md'
                - 'labboard/features/i2c-scanner.md'
                - 'labboard/features/dht11-monitor.md'
            - 'labboard/schematics.md'
            - 'labboard/firmware-update.md'
            - 'labboard/revisions.md'
        - "Side panels":
            - 'side-panels/index.md'
            - 'side-panels/io-panel.md'
            - 'side-panels/sensor-panel.md'
            - 'side-panels/audio-panel.md'
    - "Mini Control Board X3":
        - 'mini-control-board-x3/index.md'
        - 'mini-control-board-x3/revisions.md'
    - "RoboBoard X4":
        - 'roboboard-x4/index.md'
        - 'Getting started' : 'roboboard-x4/getting-started.md'
        - 'Arduino API' : 'roboboard-x4/arduino-api.md'
        - 'Qwiic' : 'roboboard-x4/qwiic.md'
        - 'MEMS' : 'roboboard-x4/mems.md'
        - 'GPIO' : 'roboboard-x4/gpio.md'
        - 'Board' : 'roboboard-x4/board.md'
        - 'X4.config' : 'roboboard-x4/config.md'
        - 'X4.button' : 'roboboard-x4/button.md'
        - 'X4.led' : 'roboboard-x4/led.md'
        - 'X4.rgb' : 'roboboard-x4/rgb.md'
        - 'X4.dc' : 'roboboard-x4/dc.md'
        - 'X4.servo' : 'roboboard-x4/servo.md'
        - 'X4.module' : 'roboboard-x4/module.md'
        - 'X4.function' : 'roboboard-x4/function.md'
    - "TBUS Modules":
        - 'modules/index.md'
        - 'Programming' : 'modules/programming.md'
        - 'modules/03.md'
        - 'modules/04.md'
        - 'modules/11.md'
        - 'modules/14.md'
        - 'modules/15.md'
        - 'modules/22.md'
    - "Remote control":
        - 'remote-control/index.md'
        - "Arduino":
            - 'remote-control/arduino/index.md'
            - 'remote-control/arduino/ModuleData.md'
            - 'remote-control/arduino/MotorDriver.md'
            - 'remote-control/arduino/TotemModule.md'
            - 'remote-control/arduino/TotemRobot.md'
        - "Totem App":
            - 'remote-control/app/index.md'
            - 'remote-control/app/control-robot.md'
            - 'remote-control/app/custom-function.md'
        - "PS3/PS4 controller" : remote-control/ps-controller.md
